name: SMA Crossover Checker

on:
  schedule:
    # Run at 12 PM Eastern Time (which is 4 PM UTC during Daylight Saving Time and 5 PM UTC otherwise)
    - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      sendTestEmail:
        description: 'Send a test email (true/false)'
        required: true
        default: 'false'
jobs:
  check_sma_crossover:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install yfinance pandas

    - name: Run SMA crossover script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python alert.py
      
  send_test_email:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.sendTestEmail == 'true' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install yfinance pandas
    - name: Send Test Email
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        SEND_TEST_EMAIL: 'true'
      run: python alert.py
